"""Writes an ATT&CK Navigator layer file.

The layer JSON shape (``techniques[].techniqueID/score/color``, ``gradient``,
``legendItems``, ``versions``) is the documented public format used by
https://github.com/mitre-attack/attack-navigator (Apache License 2.0). Only
that documented file format is implemented here -- no Navigator source was
copied.
"""

from __future__ import annotations

from .models import COVERAGE_COLOR, COVERAGE_SCORE, Coverage, TechniqueResult

_LEGEND = [
    (Coverage.DETECTED_VISIBLE, "Detected & visible"),
    (Coverage.DETECTED_BLIND, "Detected but blind (rule exists, telemetry missing)"),
    (Coverage.VISIBLE_UNDETECTED, "Visible but undetected (telemetry exists, no rule)"),
    (Coverage.NO_COVERAGE, "No coverage"),
]


def build_layer(
    results: dict[str, TechniqueResult],
    name: str = "attackgap coverage",
    description: str = "",
) -> dict:
    techniques = []
    for technique_id, result in sorted(results.items()):
        comment_parts = [result.reason]
        if result.rules:
            comment_parts.append("Rules: " + "; ".join(sorted(set(result.rules))))
        techniques.append(
            {
                "techniqueID": technique_id,
                "score": COVERAGE_SCORE[result.coverage],
                "color": COVERAGE_COLOR[result.coverage],
                "comment": " | ".join(p for p in comment_parts if p),
                "enabled": True,
            }
        )

    return {
        "name": name,
        # ATT&CK content version is intentionally omitted so Navigator uses
        # its current dataset. The input bundle may be from any ATT&CK release.
        "versions": {"navigator": "4.9.1", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": description or "Generated by attackgap",
        "techniques": techniques,
        "gradient": {
            "colors": [
                COVERAGE_COLOR[Coverage.NO_COVERAGE],
                COVERAGE_COLOR[Coverage.VISIBLE_UNDETECTED],
                COVERAGE_COLOR[Coverage.DETECTED_BLIND],
                COVERAGE_COLOR[Coverage.DETECTED_VISIBLE],
            ],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [{"label": label, "color": COVERAGE_COLOR[c]} for c, label in _LEGEND],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }
